name: Test in Docker

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    # Cypress Docker image from https://hub.docker.com/r/cypress
    # with browsers pre-installed
    container:
      image: cypress/browsers:latest
      options: --user 1001

    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: docker run -it -v "C:/Users/Dmytro Kosenko/OneDrive/Рабочий стол/QA Automation JS Course/0. Course/homework:/e2e" -w /e2e cypress/included:13.2.0 npm run cy_run_chrome_headed spec cypress/e2e/Custom_scenarious/guru_testing.cy.js
